### PR TITLE
Use URL Interface

### PR DESCRIPTION
**Pull request by sjehuda**
Replace protocol by fjyt:// using URL interface instead of regex

### CODE REVIEW

**Comment by sjehuda** [comment]
Here is another userscript that extracts the page id.

```javascript
// ==UserScript==
// @name         Firejail :: YT Handler
// @description  Relay Youtube URL's to external firejailed media player.
// @include      *
// @grant        none
// ==/UserScript==

const keywords = [
  '.youtube.com',
  '.youtu.be']

for (let i = 0; i < keywords.length; i++) {
  for (const elem of document.querySelectorAll('a[href*="' + keywords[i] + '"]')) {
    url = new URL(elem.href);
    switch (true) {
    case (url.origin.endsWith('.be')):
      pageID = url.pathname.slice(1);
      break;
    case (url.pathname.startsWith('/embed')):
      pageID = url.pathname.split('/')[2];
      break;
    case (url.pathname.startsWith('/watch')):
      pageID = url.searchParams.get('v');
      break;
    default:
      continue;
    }
    elem.href = 'fjyt://' + pageID;
  }
}
```

**Review by glitsj16 — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by glitsj16** [comment]
> Just to be certain, which one is it? (1 or 2)

Option 1. The fjyt.user.js simply needs to change the `scheme` to `fjyt` for the custom mimetype handler to be called.

**Comment by sjehuda** [comment]
I've missed `.be` in the previous one (notice it has `.com` instead).
I've fixed it and added several improvements at #2.
I apologies for the trouble.

**Comment by glitsj16** [comment]
> I've missed .be in the previous one (notice it has .com instead).
I've fixed it and added several improvements at #2.
I apologies for the trouble.

Great. No need to apologize, I'm grateful for your time and effort to overhaul the fjyt.user.js :+1:

**Comment by sjehuda** [comment]
You're most welcome.
I'm glade to contribute.

Thank you, for managing and packaging this project.
A genuine sandbox and permission manager is essential.

**Pull request merged**
